services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ocadays2024-odoo-data:/var/lib/odoo
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ocadays2024-db-data:/var/lib/postgresql/data
volumes:
  ocadays2024-odoo-data:
  ocadays2024-db-data:
